
stages:
  train_pipeline:
    cmd: python src/pipeline/training_pipeline.py
    deps:
      - src/pipeline/training_pipeline.py
      - src\components\data_ingestion.py
      - src\components\data_transformation.py
      - src\components\model_trainer.py
    outs:
      - artifacts/train.csv
      - artifacts/test.csv
      - artifacts/raw.csv
      - artifacts/text_preprocessor.pkl
      - artifacts/text_classifier_model.pkl

      